2020/03/22 17:56:07 [error] 7#7: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost:8080"
2020/03/22 17:56:07 [error] 7#7: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: app, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost:8080", referrer: "http://localhost:8080/"
2020/03/22 17:56:18 [error] 7#7: *34 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 17:56:48 [error] 7#7: *36 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 17:57:18 [error] 7#7: *38 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 17:57:48 [error] 7#7: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 17:58:18 [error] 7#7: *42 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 17:58:48 [error] 7#7: *44 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 17:59:18 [error] 7#7: *46 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 17:59:48 [error] 7#7: *48 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:00:18 [error] 7#7: *50 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:00:48 [error] 7#7: *52 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:01:18 [error] 7#7: *54 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:01:48 [error] 7#7: *56 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:02:18 [error] 7#7: *58 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:02:48 [error] 7#7: *60 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:03:18 [error] 7#7: *62 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:03:49 [error] 7#7: *64 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:04:19 [error] 7#7: *66 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:04:49 [error] 7#7: *68 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:05:19 [error] 7#7: *70 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:05:49 [error] 7#7: *72 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:06:19 [error] 7#7: *74 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:06:49 [error] 7#7: *76 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:07:19 [error] 7#7: *78 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:07:49 [error] 7#7: *80 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:08:19 [error] 7#7: *82 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:08:49 [error] 7#7: *84 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:09:19 [error] 7#7: *86 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:09:49 [error] 7#7: *88 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:10:19 [error] 7#7: *90 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:10:49 [error] 7#7: *92 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:11:20 [error] 7#7: *94 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:11:50 [error] 7#7: *96 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:12:20 [error] 7#7: *98 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:12:50 [error] 7#7: *100 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:13:20 [error] 7#7: *102 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:13:50 [error] 7#7: *104 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:14:20 [error] 7#7: *106 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:14:50 [error] 7#7: *108 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:15:20 [error] 7#7: *110 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:15:50 [error] 7#7: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:16:20 [error] 7#7: *114 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:16:50 [error] 7#7: *116 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:17:20 [error] 7#7: *118 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:17:50 [error] 7#7: *120 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:18:20 [error] 7#7: *122 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:18:50 [error] 7#7: *124 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:19:21 [error] 7#7: *126 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:19:51 [error] 7#7: *128 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:20:21 [error] 7#7: *130 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:20:51 [error] 7#7: *132 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:21:21 [error] 7#7: *134 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:21:51 [error] 7#7: *136 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:22:21 [error] 7#7: *138 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:22:51 [error] 7#7: *140 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:23:21 [error] 7#7: *142 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:23:51 [error] 7#7: *144 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:24:21 [error] 7#7: *146 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:24:51 [error] 7#7: *148 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:25:21 [error] 7#7: *150 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:25:51 [error] 7#7: *152 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:26:21 [error] 7#7: *154 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:26:51 [error] 7#7: *156 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:27:22 [error] 7#7: *158 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:27:52 [error] 7#7: *160 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:28:22 [error] 7#7: *162 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:28:52 [error] 7#7: *164 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:29:22 [error] 7#7: *166 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:29:52 [error] 7#7: *168 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:30:22 [error] 7#7: *170 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
2020/03/22 18:30:52 [error] 7#7: *172 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://0.0.0.0:9001", host: "localhost"
